In [1]:
import numpy as np 

In [2]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a * b

array([ 2,  6, 12, 20])

In [3]:
#Creating Numpy arrays

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [6]:
np.random.randint(0,10,10)

array([2, 6, 7, 6, 3, 8, 6, 5, 7, 0])

In [7]:
np.random.normal(10,4,(3,4))

array([[13.4807039 , 12.86545121, 12.96141673, 14.58601029],
       [ 9.74459276,  7.04639884,  7.22409599,  9.65867483],
       [13.02703507,  8.34280911, 11.87439491,  7.44317713]])

In [8]:
# Attib utes of numpy arrays

In [9]:
#ndim : boyut sayısı
#shape : boyut bilgisi
#size : toplam eleman sayısı 
#dtype : array veri type

In [10]:
a = np.random.randint(10,size = 5)

In [11]:
a

array([9, 1, 3, 1, 0])

In [13]:
a.ndim # Tek boyutlu 

1

In [14]:
a.shape

(5,)

In [16]:
a.size # toplam eleman sayısı 

5

In [17]:
a.dtype

dtype('int32')

In [19]:
ar = np.random.randint(10,size = 9)

In [21]:
ar

array([2, 4, 0, 4, 8, 4, 4, 9, 8])

In [20]:
ar.reshape(3,3)

array([[2, 4, 0],
       [4, 8, 4],
       [4, 9, 8]])

In [22]:
# Index selection 

In [23]:
K = np.random.randint(10,size = 10)

In [24]:
K[0]

3

In [25]:
K[0:5]

array([3, 3, 8, 8, 7])

In [26]:
K[0] = 999

In [27]:
K[0]

999

In [28]:
m = np.random.randint(10,size = (3,5))

In [29]:
m 

array([[5, 2, 1, 3, 9],
       [7, 9, 8, 9, 5],
       [8, 8, 1, 9, 3]])

In [30]:
m[0][0]

5

In [31]:
m[1][1]

9

In [32]:
m[1][1] = 72

In [33]:
m[1][1]

72

In [35]:
v = np.arange(0,30,3)

In [ ]:
#Fancy İndex

In [36]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [37]:
catch = [1,2,3]
v[catch]

array([3, 6, 9])

In [38]:
l = np.array([1,2,3,4,5])

In [39]:
l

array([1, 2, 3, 4, 5])

In [40]:
l[l<3]

array([1, 2])

In [41]:
# Mathmetical Operations

In [43]:
v = np.array([1,2,3,4,5])
s = v / 5
b = v * 5 / 10
n = v ** 2

In [44]:
s

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [45]:
b

array([0.5, 1. , 1.5, 2. , 2.5])

In [46]:
n

array([ 1,  4,  9, 16, 25])

In [49]:
# 5 * x0 + x1 = 12
# x0 + 3 * x1 = 10


a = np.array([[5,1],[1,3]])
b = np.array([12,10])

np.linalg.solve(a,b)

array([1.85714286, 2.71428571])