In [1]:
import numpy as np 

In [3]:
data = np.random.randn(3,2)

In [4]:
data

array([[-1.36378691, -0.5648162 ],
       [ 1.27674573, -0.29982448],
       [-1.46226978, -0.79356   ]])

In [7]:
new_data = data ** 10

In [8]:
data.shape 

(3, 2)

In [9]:
new_data.shape

(3, 2)

In [10]:
data.dtype

dtype('float64')

In [11]:
list = [3,6.5,0,1,9]

In [12]:
array = np.array(list)

In [13]:
array

array([3. , 6.5, 0. , 1. , 9. ])

In [14]:
list2  = [[1,2,3],[4,5,6]]
array2  = np.array(list2)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
array3  = np.zeros(10)

In [20]:
array3  = np.zeros(10,dtype = int)

In [22]:
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
array4 = np.ones((1,5))

In [24]:
array4

array([[1., 1., 1., 1., 1.]])

In [25]:
array3.astype(np.float64)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
dizi  = np.arange(10)
dizi2 =  dizi[:3]

print(dizi)
print(dizi2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]


In [32]:
dizi3 = [[1,2,3],[3,4,5],[6,7,8]]
print(dizi3[0])
print(dizi3[0][0])
print(dizi3[0][:1])

[1, 2, 3]
1
[1]


In [34]:
dizi4  =  np.arange(20).reshape(5,4)
print(dizi4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [35]:
dizi5  =  np.arange(20).reshape(4,5)
print(dizi5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [37]:
np.dot(dizi5.T,dizi5)

array([[350, 380, 410, 440, 470],
       [380, 414, 448, 482, 516],
       [410, 448, 486, 524, 562],
       [440, 482, 524, 566, 608],
       [470, 516, 562, 608, 654]])

In [38]:
dizi5.mean()

9.5

In [47]:
dizi.sum()

45

In [48]:
dizi5.mean(1) #satır

array([ 2.,  7., 12., 17.])

In [49]:
dizi5.mean(0)#sutun 

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [58]:
dizi6 = np.array([1,1,1,23,23])

In [59]:
np.unique(dizi6)

array([ 1, 23])